### ISSUE TITLE
GPU -1 fails

### ISSUE THREAD

**Issue by udnaan** [liamjones/PaintsChainer-Docker#2]
docker run -p 8000:8000 -e PAINTCHAINER_GPU=-1 liamjones/paintschainer-docker       2.6m  Tue Jan 31 11:48:45 2017
/opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
GPU: 0
start
load model
Traceback (most recent call last):
  File "server.py", line 109, in <module>
    painter = cgi_exe.Painter(gpu=args.gpu)
  File "./cgi-bin/paint_x2_unet/cgi_exe.py", line 35, in __init__
    cuda.get_device(self.gpu).use()
  File "/opt/conda/lib/python3.5/site-packages/chainer/cuda.py", line 178, in get_device
    check_cuda_available()
  File "/opt/conda/lib/python3.5/site-packages/chainer/cuda.py", line 83, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.

original error: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by liamjones** [comment]
Ah, my bad - typo in the readme. The environment variable name is PAINT**S**CHAINER_GPU. Let me know if that fixes it for you and I'll go update the readme in the meantime.

**Comment by udnaan** [comment]
Oh good. This fixes it. Feel free to update the readme.

**Comment by udnaan** [comment]
Another thing you might want to take care of when you are updating the readme is to update the command to have `-docker` postfixed as that is the image name in docker repo.

**Comment by liamjones** [comment]
Ah, good catch, I renamed the project before publish - will do.
